"""
Constantes de branding para android-gradle-analyzer.
Uso discreto: header, exit line, footer de exports.
"""

AUTHOR      = "pfranccino"
AUTHOR_URL  = "https://pfranccino.dev"
VERSION     = "1.0.5"
TOOL_NAME   = "android-gradle-analyzer"

# Textos reutilizables
HEADER_CREDIT   = f"by [link={AUTHOR_URL}]{AUTHOR}[/link]"   # Rich markup
EXIT_LINE       = f"made with care · {AUTHOR_URL}"
EXPORT_FOOTER   = f"Generated by {TOOL_NAME} · {AUTHOR_URL}"
VERSION_STRING  = f"{TOOL_NAME} {VERSION} · by {AUTHOR} · {AUTHOR_URL}"
